[package]
name = "search_for"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
num_cpus = "1.13.1"
regex = "1.5.4"

clap = { version = "3.0.5", features = ["derive"] }